In [1]:
import pandas as pd

In [2]:
pca_input = pd.read_csv("GSE69360_RNAseq.counts_edit.csv")

In [31]:
column_header = list(pca_input.columns)
column_header

['Geneid',
 'Length',
 'AA_Colon',
 'AA_Heart',
 'AA_Kidney',
 'AA_Liver',
 'AA_Lung',
 '   AA_Stomach',
 'AF_Colon',
 'AF_Stomach',
 'BA_Colon',
 'BA_Heart',
 'BA_Kidney',
 'BA_Liver',
 'BA_Lung',
 'BA_Stomach',
 'BF_Colon',
 'BF_Stomach',
 'OA_Stomach1',
 'OA_Stomach2',
 'OA_Stomach3']

In [25]:
new_geneid = pca_input['Geneid'].apply(lambda x: x.split('.')[0])
pca_input.head()

,Geneid,Length,AA_Colon,AA_Heart,AA_Kidney,AA_Liver,AA_Lung,AA_Stomach,AF_Colon,AF_Stomach,...,BA_Heart,BA_Kidney,BA_Liver,BA_Lung,BA_Stomach,BF_Colon,BF_Stomach,OA_Stomach1,OA_Stomach2,OA_Stomach3
0,ENSG00000223972.4,1756,1,0,0,0,0,0,7,2,...,0,0,0,7,0,0,3,3,1,0
1,ENSG00000227232.4,2073,36,21,32,28,17,17,102,41,...,24,22,6,49,2,153,157,38,53,18
2,ENSG00000243485.2,1021,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000237613.2,1219,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000268020.2,947,0,0,0,0,0,0,0,0,...,0,0,0,4,0,0,0,0,0,0

In [20]:
pca_input.groupby(new_geneid).sum()['AA_Colon'].head()

Geneid
ENSG00000000003    735
ENSG00000000005     16
ENSG00000000419    474
ENSG00000000457    329
ENSG00000000460    191
Name: AA_Colon, dtype: int64

In [26]:
pca_input.groupby(new_geneid).max()['Length'].head()

Geneid
ENSG00000000003    2968
ENSG00000000005    1610
ENSG00000000419    1207
ENSG00000000457    6876
ENSG00000000460    6354
Name: Length, dtype: int64

In [9]:
try_df = pd.DataFrame()

In [10]:
try_df['gene']= ['gene1','gene1','gene1','gene1','gene2']
try_df['length'] = [10,20,30,40,10]

In [11]:
try_df

    gene  length
0  gene1      10
1  gene1      20
2  gene1      30
3  gene1      40
4  gene2      10

In [23]:
try_df.groupby(['gene']).max()['length']

gene
gene1    40
gene2    10
Name: length, dtype: int64

In [27]:
pca_input.groupby(new_geneid)['AA_Colon'].sum().head()

Geneid
ENSG00000000003    735
ENSG00000000005     16
ENSG00000000419    474
ENSG00000000457    329
ENSG00000000460    191
Name: AA_Colon, dtype: int64

In [35]:
pca_input.groupby(new_geneid)['AA_Colon'].sum().head().values

array([735,  16, 474, 329, 191])

In [29]:
list(try_df.columns)

['gene', 'length']

In [32]:
try_df

    gene  length
0  gene1      10
1  gene1      20
2  gene1      30
3  gene1      40
4  gene2      10

In [33]:
try_df['geneid'] = new_geneid
try_df

    gene  length           geneid
0  gene1      10  ENSG00000223972
1  gene1      20  ENSG00000227232
2  gene1      30  ENSG00000243485
3  gene1      40  ENSG00000237613
4  gene2      10  ENSG00000268020

In [46]:
pca_input = pd.read_csv("GSE69360_RNAseq.counts.csv",sep='\t')

In [49]:
pca_input.head(20)

,Geneid,Chr,Start,End,Strand,Length,AA_Colon,AA_Heart,AA_Kidney,AA_Liver,...,BA_Heart,BA_Kidney,BA_Liver,BA_Lung,BA_Stomach,BF_Colon,BF_Stomach,OA_Stomach1,OA_Stomach2,OA_Stomach3
0,ENSG00000223972.4,chr1;chr1;chr1;chr1,11869;12595;12975;13221,12227;12721;13052;14412,+;+;+;+,1756,1,0,0,0,...,0,0,0,7,0,0,3,3,1,0
1,ENSG00000227232.4,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,14363;14970;15796;16607;16854;17233;17498;1760...,14829;15038;15947;16765;17055;17368;17504;1774...,-;-;-;-;-;-;-;-;-;-;-;-;-,2073,36,21,32,28,...,24,22,6,49,2,153,157,38,53,18
2,ENSG00000243485.2,chr1;chr1;chr1,29554;30267;30976,30039;30667;31109,+;+;+,1021,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ENSG00000237613.2,chr1;chr1;chr1,34554;35245;35721,35174;35481;36081,-;-;-,1219,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ENSG00000268020.2,chr1;chr1,52473;54830,53312;54936,+;+,947,0,0,0,0,...,0,0,0,4,0,0,0,0,0,0
5,ENSG00000240361.1,chr1,62948,63887,+,940,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,ENSG00000186092.4,chr1,69091,70008,+,918,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,ENSG00000238009.2,chr1;chr1;chr1;chr1;chr1;chr1;chr1,89295;92091;110953;112700;120721;129055;133374,91629;92240;111357;112804;120932;129223;133566,-;-;-;-;-;-;-,3569,3,0,1,2,...,1,0,0,5,0,5,4,1,2,1
8,ENSG00000239945.1,chr1;chr1,89551;90287,90050;91105,-;-,1319,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,ENSG00000233750.3,chr1,131025,134836,+,3812,0,0,0,0,...,0,1,0,6,0,3,1,1,0,2
10,ENSG00000237683.5,chr1;chr1,134901;137621,135802;139379,-;-,2661,5,5,4,31,...,7,3,1,22,4,32,17,15,27,3
11,ENSG00000268903.1,chr1,135141,135895,-,755,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
12,ENSG00000269981.1,chr1,137682,137965,-,284,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,ENSG00000239906.1,chr1;chr1,139790;140075,139847;140339,-;-,323,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
14,ENSG00000241860.2,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1,141474;146386;155767;164263;165884;168100;1686...,143011;149707;155831;164791;165942;168165;1687...,-;-;-;-;-;-;-;-;-;-,6195,4,4,3,4,...,6,12,1,11,0,30,27,4,10,1
15,ENSG00000222623.1,chr1,157784,157887,-,104,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,ENSG00000241599.1,chr1;chr1,160446;161314,160690;161525,+;+,457,5,1,1,0,...,0,0,1,1,0,3,4,1,4,0
17,ENSG00000228463.4,chr1;chr1;chr1;chr1;chr1;chr1;chr1,227615;234355;236112;238418;257268;259017;267096,228776;234484;237955;238567;257672;259121;267253,-;-;-;-;-;-;-,3954,1,3,5,3,...,8,4,1,15,1,24,13,1,4,0
18,ENSG00000241670.2,chr1,228292,228775,-,484,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,ENSG00000237094.7,chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;chr1;c...,317720;319968;320881;321032;322038;322672;3238...,317781;320653;320938;321290;322228;323073;3240...,+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+,6869,0,1,0,2,...,1,0,0,1,0,1,6,1,0,0

In [ ]:
new_geneid = pca_input['Geneid'].apply(lambda x: x.split('.')[0])
#pca_input.groupby(new_geneid,sort=False).sum()['AA_Heart']

In [61]:
new_geneid = pca_input['Geneid'].apply(lambda x: x.split('.')[0])
new_geneid.nunique()

57820